import { test, expect } from '@playwright/test'
let token = ''; let characterId = ''; let chatId = ''
const api = 'http://127.0.0.1:3400/api/v1'; const admin = 'http://127.0.0.1:3410/api/v1/admin'
test.beforeAll(async ({ request }) => { const login = await request.post(admin + '/login', { data: { email: 'ui-admin@example.test', password: 'UITestAdmin#123' } }); expect(login.ok()).toBeTruthy(); const at = (await login.json()).token; const headers = { authorization: 'Bearer ' + at }; const ch = await request.post(admin + '/characters', { headers, data: { name: '视觉测试角色', description: '真实测试数据库中的角色设定', opening: '欢迎开启新的故事', gender: 'female', cost: 10, published: true, tags: ['测试'] } }); expect(ch.ok()).toBeTruthy(); characterId = (await ch.json()).id; const user = await request.post(admin + '/users', { headers, data: { name: '视觉测试用户', email: 'ui-user@example.test', password: 'UITestUser#123', balance: 123 } }); expect(user.ok()).toBeTruthy(); token = (await (await request.post(api + '/auth/login', { data: { email: 'ui-user@example.test', password: 'UITestUser#123' } })).json()).token; chatId = (await (await request.post(api + '/conversations', { headers: { authorization: 'Bearer ' + token }, data: { characterId } })).json()).id })
test.beforeEach(async ({ page }) => { await page.addInitScript(token => { if (!sessionStorage.getItem('fixture-auth-initialized')) { localStorage.setItem('user_token', token); sessionStorage.setItem('fixture-auth-initialized', 'true') } }, token) })
test('home keeps reference composition and uses actual database roles and balance', async ({ page }) => { await page.goto('/'); await expect(page.getByText('与心动的角色')).toBeVisible(); await expect(page.getByText('角色发现')).toBeVisible(); await expect(page.getByRole('heading', { name: '视觉测试角色' })).toBeVisible(); await expect(page.getByText('123', { exact: true }).first()).toBeVisible(); await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true }) })
test('character favorite and creating a chat are functional', async ({ page }) => { await page.goto('/characters/' + characterId); await expect(page.getByRole('heading', { name: '角色简介' })).toBeVisible(); await page.getByRole('button', { name: '收藏角色', exact: true }).click(); await expect(page.getByRole('button', { name: '取消收藏' })).toBeVisible(); await page.getByRole('button', { name: '开始聊天', exact: true }).click(); await expect(page).toHaveURL(/\/conversations\//); await expect(page.getByText('欢迎开启新的故事')).toBeVisible() })
test('sending without a model reports an error and does not simulate a reply', async ({ page }) => { await page.goto('/conversations/' + chatId); await page.getByRole('textbox', { name: '聊天消息' }).fill('需要真实模型'); await page.getByRole('button', { name: '发送消息' }).click(); await expect(page.getByRole('alert')).toContainText('尚未配置'); await expect(page.getByText('欢迎开启新的故事')).toBeVisible(); await expect(page.getByRole('textbox', { name: '聊天消息' })).toHaveValue('需要真实模型') })
test('actual profile balance and real empty gallery, transactions and packages render', async ({ page }) => { for (const [route, heading] of [['/me', '会员权益'], ['/gallery', '暂无图片'], ['/me/transactions', '消费记录'], ['/me/wallet', '积分充值'], ['/me/membership', '会员权益'], ['/me/settings', '设置']]) { await page.goto(route); await expect(page.getByText(heading).first()).toBeVisible(); const widths = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: document.documentElement.scrollWidth })); expect(widths.content, route).toBeLessThanOrEqual(widths.viewport + 1) }; await page.goto('/me'); await expect(page.locator('.wallet-panel strong')).toHaveText('123') })
test('chat and profile remain usable at 360px and character details at 390px', async ({ page }) => { await page.setViewportSize({ width: 360, height: 800 }); for (const route of ['/conversations/' + chatId, '/conversations', '/gallery', '/me', '/me/transactions', '/me/wallet', '/me/settings']) { await page.goto(route); await expect(page.locator('.mobile-nav')).toBeVisible(); await expect(page.getByRole('link', { name: '登录', exact: true })).toHaveCount(0); const widths = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: document.documentElement.scrollWidth })); expect(widths.content, route).toBeLessThanOrEqual(widths.viewport + 1) }; await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/characters/' + characterId); await expect(page.getByRole('button', { name: '开始聊天' })).toBeVisible(); await page.screenshot({ path: 'test-results/character-mobile.png', fullPage: true }) })
test('image uploads persist across reload and support favorite, preview and deletion', async ({ page, request }) => {
  await page.goto('/gallery')
  await page.locator('input[type=file]').setInputFiles({ name: 'upload-test.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByRole('button', { name: '收藏图片', exact: true })).toBeVisible(); await page.reload(); await page.getByRole('button', { name: '收藏图片', exact: true }).click(); await expect(page.getByRole('button', { name: '取消图片收藏', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^预览 / }).click(); await expect(page.getByRole('heading', { name: '图片预览' })).toBeVisible(); await expect(page.getByRole('link', { name: '保存图片' })).toBeVisible(); await page.getByRole('button', { name: '关闭', exact: true }).click()
  const headers = { authorization: 'Bearer ' + token }; const images = await (await request.get(api + '/images', { headers })).json(); expect(images).toHaveLength(1); expect(images[0].url).toMatch(/^data:image\/png;base64,/); expect(images[0].favorite).toBe(true)
  await page.getByRole('button', { name: '删除图片', exact: true }).click(); await page.getByRole('button', { name: '确认删除', exact: true }).click(); await expect(page.getByText('暂无图片', { exact: false })).toBeVisible(); expect(await (await request.get(api + '/images', { headers })).json()).toHaveLength(0)
})

test('login registration and account editing work in the browser', async ({ page }) => { await page.goto('/'); await page.evaluate(() => localStorage.removeItem('user_token')); await page.reload(); await page.getByRole('link', { name: '登录', exact: true }).click(); await page.getByRole('button', { name: '没有账号，去注册' }).click(); await page.getByLabel('昵称', { exact: true }).fill('新注册用户'); await page.getByLabel('邮箱', { exact: true }).fill('ui-register@example.test'); await page.getByLabel('密码', { exact: true }).fill('RegisterUI#123'); await page.getByRole('button', { name: '注册并登录' }).click(); await expect(page.getByRole('heading', { name: '新注册用户' })).toBeVisible(); await page.goto('/me/settings'); await page.getByLabel('昵称', { exact: true }).fill('修改后的用户'); await page.getByRole('button', { name: '保存设置' }).click(); await expect(page.getByRole('status')).toContainText('账号已更新'); await page.getByRole('button', { name: '退出登录' }).click(); await expect(page.getByRole('link', { name: '登录', exact: true })).toBeVisible() })

test('real Core streaming appears before completion, renders Markdown and persists usage once', async ({ page, request }) => {
  const at = (await (await request.post(admin + '/login', { data: { email: 'ui-admin@example.test', password: 'UITestAdmin#123' } })).json()).token
  const model = await request.post(admin + '/models', { headers: { authorization: 'Bearer ' + at }, data: { name: 'UI streaming fixture', baseUrl: 'http://host.docker.internal:3420/v1', model: 'fixture-stream', apiKey: 'ui-stream-fixture', inputRate: 1, outputRate: 1, cacheReadRate: 1 } }); expect(model.ok()).toBeTruthy()
  await page.goto('/conversations/' + chatId)
  await page.getByRole('textbox', { name: '聊天消息' }).fill('测试实时回复')
  await page.getByRole('button', { name: '发送消息' }).click()
  await expect(page.locator('.stream-reply')).toContainText('角色正在思考')
  await expect(page.locator('.messages')).not.toContainText('private fixture reasoning')
  await expect(page.locator('.stream-reply')).toContainText('第一段回复')
  await expect(page.locator('.stream-reply')).not.toContainText('第二段回复')
  await expect(page.getByRole('button', { name: '停止生成' })).toBeVisible()
  await expect(page.locator('.stream-reply em')).toHaveText('轻轻挥手')
  await page.screenshot({ path: 'test-results/chat-streaming-desktop.png', fullPage: true })
  await expect(page.getByRole('button', { name: '发送消息' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '聊天消息' })).toHaveValue('')
  await expect(page.locator('.markdown-bubble strong')).toHaveText('很高兴见到你')
  await expect(page.locator('.markdown-bubble pre code')).toContainText('console.log')
  const headers = { authorization: 'Bearer ' + token }
  const history = await (await request.get(api + '/conversations/' + chatId + '/messages', { headers })).json(); expect(history).toHaveLength(3); expect(history[2].usage.cachedTokens).toBe(800)
  const wallet = await (await request.get(api + '/wallet', { headers })).json(); expect(wallet.balance).toBe(113); expect(wallet.frozen).toBe(0)
  await page.reload(); await expect(page.locator('.markdown-bubble strong')).toHaveText('很高兴见到你'); await expect(page.locator('.charge-strip')).toContainText('113')
  await page.setViewportSize({ width: 360, height: 800 })
  await page.getByRole('textbox', { name: '聊天消息' }).fill('停止后可重试')
  await page.getByRole('button', { name: '发送消息' }).click(); await expect(page.locator('.stream-reply')).toContainText('第一段回复')
  await page.getByRole('button', { name: '停止生成' }).click()
  await expect(page.getByRole('alert')).toContainText('已停止')
  await expect(page.getByRole('textbox', { name: '聊天消息' })).toHaveValue('停止后可重试')
  await expect.poll(async () => (await (await request.get(api + '/wallet', { headers })).json()).frozen).toBe(0)
  expect((await (await request.get(api + '/wallet', { headers })).json()).balance).toBe(113)
  expect(await (await request.get(api + '/conversations/' + chatId + '/messages', { headers })).json()).toHaveLength(3)
  const widths = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: document.documentElement.scrollWidth })); expect(widths.content).toBeLessThanOrEqual(widths.viewport + 1)
  await expect(page.locator('.charge-strip')).toContainText('113')
  const composer = await page.locator('.composer').boundingBox(); const nav = await page.locator('.mobile-nav').boundingBox(); expect(composer!.y + composer!.height).toBeLessThanOrEqual(nav!.y)
  await page.screenshot({ path: 'test-results/chat-stopped-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '发送消息' }).click(); await expect(page.locator('.stream-reply')).toContainText('第一段回复')
  await page.getByRole('link', { name: '返回聊天列表' }).click(); await expect(page).toHaveURL(/\/conversations$/)
  await expect.poll(async () => (await (await request.get(api + '/wallet', { headers })).json()).frozen).toBe(0)
  expect(await (await request.get(api + '/conversations/' + chatId + '/messages', { headers })).json()).toHaveLength(3)
  await page.goto('/conversations/' + chatId)
  await page.getByRole('textbox', { name: '聊天消息' }).fill('long-stream')
  await page.getByRole('button', { name: '发送消息' }).click()
  await expect(page.locator('.stream-reply')).toContainText('角色正在思考')
  const bubble = page.locator('.stream-reply .markdown-bubble')
  await expect(bubble).toContainText('雨落在书店门前')
  const firstLength = (await bubble.innerText()).length
  expect(firstLength).toBeLessThan(500)
  await expect.poll(async () => (await bubble.innerText()).length).toBeGreaterThan(firstLength + 150)
  await expect(page.getByRole('button', { name: '停止生成' })).toBeVisible()
  await page.screenshot({ path: 'test-results/chat-long-stream-mobile.png', fullPage: true })
  await expect(page.getByRole('button', { name: '发送消息' })).toBeVisible()
  const longHistory = await (await request.get(api + '/conversations/' + chatId + '/messages', { headers })).json()
  expect(longHistory).toHaveLength(5); expect(longHistory.at(-1).content.length).toBeGreaterThan(1000)
  expect(longHistory.at(-1).content).not.toContain('private fixture reasoning')
  await expect(page.locator('.stream-reply')).toHaveCount(0)
})
