import { test, expect, type Page } from '@playwright/test'
test.describe.configure({ mode: 'serial' })
let token = ''; let userId = ''; let characterId = ''
const base = 'http://127.0.0.1:3310/api/v1/admin'
test.beforeAll(async ({ request }) => { const response = await request.post(base + '/login', { data: { email: 'ui-admin@example.test', password: 'UITestAdmin#123' } }); expect(response.ok()).toBeTruthy(); token = (await response.json()).token })
test.beforeEach(async ({ page }) => { await page.addInitScript(token => { if (!sessionStorage.getItem('fixture-auth-initialized')) { localStorage.setItem('admin_token', token); sessionStorage.setItem('fixture-auth-initialized', 'true') } }, token) })
async function navigate(page: Page, label: string) { await page.getByRole('menuitem', { name: label, exact: false }).click(); await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible() }
test('real admin login and empty PostgreSQL overview', async ({ page }) => {
  await page.goto('/'); await expect(page.getByRole('heading', { name: '欢迎回来，管理员' })).toBeVisible(); await expect(page.getByText('PostgreSQL · 已连接')).toBeVisible(); await page.screenshot({ path: 'test-results/admin-overview.png', fullPage: true })
})
test('character create, edit and publish link to user API', async ({ page, request }) => {
  await page.goto('/'); await navigate(page, '角色管理'); await page.getByRole('button', { name: '添加角色' }).click(); const dialog = page.getByRole('dialog'); await dialog.getByLabel('角色名称').fill('UI测试角色'); await dialog.getByLabel('角色设定').fill('用于隔离 schema 的角色测试'); await dialog.getByLabel('开场白').fill('欢迎开始测试故事'); await dialog.getByLabel('发布', { exact: true }).click(); await dialog.getByRole('button', { name: '保存角色' }).click(); await expect(dialog).not.toBeVisible()
  const row = page.getByRole('row').filter({ hasText: 'UI测试角色' }); await expect(row.getByText('已发布')).toBeVisible(); const publicList = await (await request.get('http://127.0.0.1:3300/api/v1/characters')).json(); characterId = publicList.find((item: any) => item.name === 'UI测试角色').id; expect(characterId).toBeTruthy()
  await row.getByRole('button', { name: '编辑', exact: true }).click(); await dialog.getByLabel('最低消息积分').fill('23'); await dialog.getByRole('button', { name: '保存角色' }).click(); await expect(dialog).not.toBeVisible(); const item = await (await request.get('http://127.0.0.1:3300/api/v1/characters/' + characterId)).json(); expect(item.cost).toBe(23); await page.screenshot({ path: 'test-results/admin-characters.png', fullPage: true })
})
test('user create and explicit credit increase and decrease', async ({ page, request }) => {
  await page.goto('/'); await navigate(page, '用户与积分'); await page.getByRole('button', { name: '添加用户' }).click(); const dialog = page.getByRole('dialog'); await dialog.getByLabel('昵称', { exact: true }).fill('UI积分用户'); await dialog.getByLabel('邮箱', { exact: true }).fill('ui-wallet@example.test'); await dialog.getByLabel('初始密码').fill('WalletUITest#123'); await dialog.getByLabel('初始积分').fill('100'); await dialog.getByRole('button', { name: '保存用户' }).click(); await expect(dialog).not.toBeVisible(); const row = page.getByRole('row').filter({ hasText: 'ui-wallet@example.test' }); await row.getByRole('button', { name: '积分调整' }).click(); await dialog.getByLabel('积分数量').fill('50'); await dialog.getByLabel('调整原因').fill('UI增加验证'); await dialog.getByRole('button', { name: '确认调整' }).click(); await expect(dialog).not.toBeVisible(); await expect(row.getByText('150 / 0')).toBeVisible()
  await row.getByRole('button', { name: '积分调整' }).click(); await dialog.getByLabel('调整方向').click(); await page.getByRole('option', { name: '扣减积分' }).click(); await dialog.getByLabel('积分数量').fill('20'); await dialog.getByLabel('调整原因').fill('UI扣减验证'); await dialog.getByRole('button', { name: '确认调整' }).click(); await expect(dialog).not.toBeVisible(); await expect(row.getByText('130 / 0')).toBeVisible()
  const login = await request.post('http://127.0.0.1:3300/api/v1/auth/login', { data: { email: 'ui-wallet@example.test', password: 'WalletUITest#123' } }); const userToken = (await login.json()).token; const wallet = await (await request.get('http://127.0.0.1:3300/api/v1/wallet', { headers: { authorization: 'Bearer ' + userToken } })).json(); expect(wallet.balance).toBe(130); expect(wallet.ledger.length).toBe(3)
  const users = await (await request.get(base + '/users', { headers: { authorization: 'Bearer ' + token } })).json(); userId = users.find((item: any) => item.email === 'ui-wallet@example.test').id
})
test('model has cache pricing and a usable calculator', async ({ page }) => {
  await page.goto('/'); await navigate(page, '模型与计费'); await page.getByRole('button', { name: '添加模型' }).click(); const dialog = page.getByRole('dialog'); await dialog.getByLabel('配置名称').fill('UI计费模型'); await dialog.getByLabel('OpenAI 兼容服务地址').fill('https://test-provider.example/v1'); await dialog.getByLabel('模型名称').fill('test-model'); await dialog.getByLabel('输入单价（积分/1k）', { exact: true }).fill('20'); await dialog.getByLabel('输出单价（积分/1k）', { exact: true }).fill('40'); await dialog.getByLabel('缓存命中单价（积分/1k）', { exact: true }).fill('2'); await dialog.getByLabel('缓存写入单价（积分/1k）', { exact: true }).fill('25'); await dialog.getByRole('button', { name: '保存模型' }).click(); await expect(dialog).not.toBeVisible(); await expect(page.getByText('20 / 40 / 2 / 25 积分/1k')).toBeVisible(); await page.getByLabel('模型', { exact: true }).click(); await page.getByRole('option', { name: 'UI计费模型' }).click(); await page.getByLabel('输入总 Token').fill('1000'); await page.getByLabel('输出 Token', { exact: true }).fill('100'); await page.getByLabel('缓存命中 Token').fill('800'); await page.getByLabel('缓存写入 Token').fill('100'); await page.getByRole('button', { name: '计算积分' }).click(); await expect(page.getByText('预计扣费')).toBeVisible(); await expect(page.locator('.ant-statistic-content-value-int').filter({ hasText: /^11$/ })).toBeVisible()
})
test('logs and ledger contain actual operations, user and character deletion work', async ({ page, request }) => {
  await page.goto('/'); await navigate(page, '积分流水'); await expect(page.getByText('UI增加验证')).toBeVisible(); await expect(page.getByText('UI扣减验证')).toBeVisible(); await navigate(page, '操作日志'); const creditRow = page.getByRole('row').filter({ hasText: '调整积分' }).first(); await expect(creditRow).toBeVisible(); await expect(creditRow).toContainText('ui-wallet@example.test'); await expect(creditRow).toContainText('ui-admin@example.test'); await expect(page.getByText('credits.adjust', { exact: true })).toHaveCount(0); await creditRow.getByRole('button', { name: '查看详情' }).click(); await expect(page.getByRole('heading', { name: '修改前', exact: true })).toBeVisible(); await page.keyboard.press('Escape')
  await navigate(page, '角色管理'); await page.getByRole('row').filter({ hasText: 'UI测试角色' }).getByRole('button', { name: '删除', exact: true }).click(); const dialog = page.getByRole('dialog'); await dialog.getByLabel('删除原因').fill('UI角色删除验证'); await dialog.getByRole('button', { name: '确认删除' }).click(); await expect(dialog).not.toBeVisible(); expect((await request.get('http://127.0.0.1:3300/api/v1/characters/' + characterId)).status()).toBe(404)
  await navigate(page, '用户与积分'); await page.getByRole('row').filter({ hasText: 'ui-wallet@example.test' }).getByRole('button', { name: '删除', exact: true }).click(); await dialog.getByLabel('删除原因').fill('UI账户删除验证'); await dialog.getByRole('button', { name: '确认删除' }).click(); await expect(dialog).not.toBeVisible(); await expect(page.getByRole('row').filter({ hasText: 'ui-wallet@example.test' })).toHaveCount(0); expect(userId).toBeTruthy()
})
test('SillyTavern JSON cards import as drafts and export downloadable JSON', async ({ page, request }) => {
  await page.goto('/'); await navigate(page, '角色管理')
  await page.locator('input[type=file]').setInputFiles({ name: 'test-card.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ spec: 'chara_card_v2', spec_version: '2.0', data: { name: '导入测试角色', description: '保留的角色设定', personality: '温和', first_mes: '来自导入角色卡的开场白', tags: ['导入'] } })) })
  const row = page.getByRole('row').filter({ hasText: '导入测试角色' }); await expect(row.getByText('已下架')).toBeVisible()
  const downloadPromise = page.waitForEvent('download'); await row.getByRole('button', { name: '导出', exact: true }).click(); const download = await downloadPromise; expect(download.suggestedFilename()).toBe('导入测试角色.json')
  const stream = await download.createReadStream(); const chunks: Buffer[] = []; for await (const chunk of stream!) chunks.push(Buffer.from(chunk)); const card = JSON.parse(Buffer.concat(chunks).toString()); expect(card.spec).toBe('chara_card_v2'); expect(card.data.first_mes).toBe('来自导入角色卡的开场白'); expect(card.data.description).toContain('温和')
  const publicList = await (await request.get('http://127.0.0.1:3300/api/v1/characters')).json(); expect(publicList.some((item: any) => item.name === '导入测试角色')).toBe(false)
})

test('model editor discovers remote names with new and stored credentials', async ({ page, request }) => {
  await page.goto('/'); await navigate(page, '模型与计费'); await page.getByRole('button', { name: '添加模型' }).click(); const dialog = page.getByRole('dialog')
  await dialog.getByLabel('配置名称').fill('浏览器生图模型'); await dialog.getByLabel('任务类型').click(); await page.getByRole('option', { name: '生图模型', exact: true }).click(); await dialog.getByLabel('OpenAI 兼容服务地址').fill('http://127.0.0.1:3320'); await dialog.getByLabel('API Key', { exact: true }).fill('ui-only-provider-secret')
  await dialog.getByRole('button', { name: '拉取模型列表' }).click(); await page.getByRole('option', { name: 'fixture-image-browser', exact: true }).click(); await expect(dialog.getByLabel('OpenAI 兼容服务地址')).toHaveValue('http://127.0.0.1:3320/v1'); await expect(dialog.getByLabel('模型名称')).toHaveValue('fixture-image-browser'); await dialog.getByRole('button', { name: '保存模型' }).click(); await expect(dialog).not.toBeVisible()
  const row = page.getByRole('row').filter({ hasText: '浏览器生图模型' }); await expect(row.getByText('默认', { exact: true })).toBeVisible(); await expect(row.getByRole('button', { name: '当前默认' })).toBeDisabled(); await row.getByRole('button', { name: '编辑', exact: true }).click(); await expect(dialog.getByLabel('API Key', { exact: true })).toHaveValue(''); await dialog.getByRole('button', { name: '拉取模型列表' }).click(); await expect(page.getByRole('option', { name: 'fixture-image-browser', exact: true })).toBeVisible(); await dialog.getByLabel('模型名称').press('Escape'); await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  const models = await (await request.get(base + '/models', { headers: { authorization: 'Bearer ' + token } })).json(); expect(JSON.stringify(models)).not.toContain('ui-only-provider-secret')
})

test('one-click default selection replaces only the default for the same task', async ({ page, request }) => {
  const headers = { authorization: 'Bearer ' + token }; const response = await request.post(base + '/models', { headers, data: { name: '备用生图模型', baseUrl: 'http://127.0.0.1:3320/v1', model: 'fixture-image-browser', apiKey: 'ui-only-provider-secret', task: 'image' } }); expect(response.ok()).toBeTruthy(); const standby = await response.json(); expect(standby.isDefault).toBe(false)
  await page.goto('/'); await navigate(page, '模型与计费'); const row = page.getByRole('row').filter({ hasText: '备用生图模型' }); await row.getByRole('button', { name: '设为默认', exact: true }).click(); await expect(row.getByText('默认', { exact: true })).toBeVisible(); await expect(row.getByRole('button', { name: '当前默认' })).toBeDisabled()
  const primary = page.getByRole('row').filter({ hasText: '浏览器生图模型' }); await primary.getByRole('button', { name: '设为默认', exact: true }).click(); await expect(primary.getByText('默认', { exact: true })).toBeVisible(); const models = await (await request.get(base + '/models', { headers })).json(); expect(models.filter((item: any) => item.task === 'image' && item.isDefault)).toHaveLength(1); expect(models.find((item: any) => item.id === standby.id).isDefault).toBe(false)
})

test('role cover uploads, uses existing images and generates using the configured image model', async ({ page, request }) => {
  await page.goto('/'); await navigate(page, '角色管理'); await page.getByRole('button', { name: '添加角色' }).click(); const editor = page.getByRole('dialog', { name: '添加角色', exact: true })
  await editor.getByLabel('角色名称').fill('UI封面角色'); await editor.getByLabel('角色设定').fill('用于角色封面编辑验证'); await editor.getByLabel('发布', { exact: true }).click()
  const uploaded = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='
  await editor.getByLabel('上传角色封面').setInputFiles({ name: 'role-cover.png', mimeType: 'image/png', buffer: Buffer.from(uploaded, 'base64') }); await expect(editor.getByAltText('角色封面预览')).toHaveAttribute('src', 'data:image/png;base64,' + uploaded)
  await editor.getByRole('button', { name: '选择已有图片', exact: true }).click(); await page.getByRole('dialog', { name: '选择已有图片', exact: true }).getByRole('button', { name: '选择图片 role-cover.png' }).click(); await editor.getByRole('button', { name: '保存角色' }).click(); await expect(editor).not.toBeVisible()
  const list = await (await request.get('http://127.0.0.1:3300/api/v1/characters')).json(); const character = list.find((item: any) => item.name === 'UI封面角色'); expect(character.image).toBe('data:image/png;base64,' + uploaded)
  await page.getByRole('row').filter({ hasText: 'UI封面角色' }).getByRole('button', { name: '编辑', exact: true }).click(); const editing = page.getByRole('dialog', { name: '编辑角色', exact: true }); await editing.getByRole('button', { name: 'AI 生成封面' }).click(); const generator = page.getByRole('dialog', { name: 'AI 生成角色封面', exact: true }); await expect(generator.getByText('浏览器生图模型 · fixture-image-browser', { exact: true })).toBeVisible(); await generator.getByLabel('封面描述').fill('银发少女，图书馆，精美角色封面'); await generator.getByRole('button', { name: '生成封面', exact: true }).click(); await expect(generator.getByAltText('生成的角色封面')).toBeVisible(); await generator.getByRole('button', { name: '使用此封面' }).click(); await editing.getByRole('button', { name: '保存角色' }).click(); await expect(editing).not.toBeVisible()
  await page.reload(); await expect(page.getByRole('row').filter({ hasText: 'UI封面角色' })).toBeVisible(); const current = await (await request.get('http://127.0.0.1:3300/api/v1/characters/' + character.id)).json(); expect(current.image).toMatch(/^data:image\/png;base64,/); expect(current.image).not.toBe(character.image)
  await navigate(page, '操作日志'); await expect(page.getByRole('row').filter({ hasText: '生成角色封面' }).first()).toBeVisible(); await page.screenshot({ path: 'test-results/admin-logs.png', fullPage: true })
})

test('mobile navigation works and all administration sections avoid page overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/'); await expect(page.getByRole('heading', { name: '欢迎回来，管理员' })).toBeVisible()
  for (const label of ['角色管理', '模型与计费', '用户与积分', '积分流水', '会员与套餐', '订单中心', '操作日志', '支付渠道', '账号设置']) { await page.getByRole('button', { name: '打开菜单' }).click(); await navigate(page, label); await expect(page.getByRole('dialog', { name: '管理导航' })).not.toBeVisible(); const width = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: document.documentElement.scrollWidth })); expect(width.content, label).toBeLessThanOrEqual(width.viewport + 1) }
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true })
})
